default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: cinic
  password:
  host: 127.0.0.1
development:
  <<: *default
  database: crm_development

test: &test
  <<: *default
  database: crm_test

production:
  <<: *default
  database: crm_production
staging:
  <<: *default
  database: crm_staging

cucumber:
  <<: *test