require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Money::CategoriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Money::Category. As you add validations to Money::Category, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Money::CategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all money_categories as @money_categories" do
      money_category = Money::Category.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:money_categories)).to eq([money_category])
    end
  end

  describe "GET show" do
    it "assigns the requested money_category as @money_category" do
      money_category = Money::Category.create! valid_attributes
      get :show, {:id => money_category.to_param}, valid_session
      expect(assigns(:money_category)).to eq(money_category)
    end
  end

  describe "GET new" do
    it "assigns a new money_category as @money_category" do
      get :new, {}, valid_session
      expect(assigns(:money_category)).to be_a_new(Money::Category)
    end
  end

  describe "GET edit" do
    it "assigns the requested money_category as @money_category" do
      money_category = Money::Category.create! valid_attributes
      get :edit, {:id => money_category.to_param}, valid_session
      expect(assigns(:money_category)).to eq(money_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Money::Category" do
        expect {
          post :create, {:money_category => valid_attributes}, valid_session
        }.to change(Money::Category, :count).by(1)
      end

      it "assigns a newly created money_category as @money_category" do
        post :create, {:money_category => valid_attributes}, valid_session
        expect(assigns(:money_category)).to be_a(Money::Category)
        expect(assigns(:money_category)).to be_persisted
      end

      it "redirects to the created money_category" do
        post :create, {:money_category => valid_attributes}, valid_session
        expect(response).to redirect_to(Money::Category.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved money_category as @money_category" do
        post :create, {:money_category => invalid_attributes}, valid_session
        expect(assigns(:money_category)).to be_a_new(Money::Category)
      end

      it "re-renders the 'new' template" do
        post :create, {:money_category => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested money_category" do
        money_category = Money::Category.create! valid_attributes
        put :update, {:id => money_category.to_param, :money_category => new_attributes}, valid_session
        money_category.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested money_category as @money_category" do
        money_category = Money::Category.create! valid_attributes
        put :update, {:id => money_category.to_param, :money_category => valid_attributes}, valid_session
        expect(assigns(:money_category)).to eq(money_category)
      end

      it "redirects to the money_category" do
        money_category = Money::Category.create! valid_attributes
        put :update, {:id => money_category.to_param, :money_category => valid_attributes}, valid_session
        expect(response).to redirect_to(money_category)
      end
    end

    describe "with invalid params" do
      it "assigns the money_category as @money_category" do
        money_category = Money::Category.create! valid_attributes
        put :update, {:id => money_category.to_param, :money_category => invalid_attributes}, valid_session
        expect(assigns(:money_category)).to eq(money_category)
      end

      it "re-renders the 'edit' template" do
        money_category = Money::Category.create! valid_attributes
        put :update, {:id => money_category.to_param, :money_category => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested money_category" do
      money_category = Money::Category.create! valid_attributes
      expect {
        delete :destroy, {:id => money_category.to_param}, valid_session
      }.to change(Money::Category, :count).by(-1)
    end

    it "redirects to the money_categories list" do
      money_category = Money::Category.create! valid_attributes
      delete :destroy, {:id => money_category.to_param}, valid_session
      expect(response).to redirect_to(money_categories_url)
    end
  end

end
